import React, { useMemo, useState } from 'react';
import { Plus, Search, Edit, Trash2, Eye, Printer, Save, X } from 'lucide-react';
import { useAuth } from '../lib/AuthContext';
import { getData, addItem, updateItem, deleteItem, generateId, formatDate } from '../lib/store';

const ASPEK = [
 {kode:'A',nama:'Mensyukuri Nikmat dan Kebaikan Allah',indikator:[
  [1,'Mengucapkan hamdalah ketika memperoleh keberhasilan atau kebahagiaan'],[2,'Mengucapkan terima kasih ketika menerima bantuan atau kebaikan'],[3,'Menggunakan fasilitas madrasah dengan baik dan tidak merusaknya'],[4,'Mindfullness dalam makan sebagai bentuk rasa syukur kepada Allah']]},
 {kode:'B',nama:'Meneladani Akhlak Rasulullah SAW',indikator:[
  [5,'Mengucapkan salam ketika bertemu guru dan teman'],[6,'Berkata jujur kepada guru, orang tua, dan teman'],[7,'Bersikap sopan kepada guru dan teman'],[8,'Mau meminta maaf dan memaafkan ketika melakukan kesalahan']]},
 {kode:'C',nama:'Membiasakan Beribadah',indikator:[
  [9,'Berdoa sebelum dan sesudah belajar'],[10,'Mengikuti salat berjamaah dengan tertib'],[11,'Membaca Al-Qur’an sesuai kemampuan'],[12,'Mengikuti kegiatan keagamaan dengan senang hati'],[13,'Menjaga ketertiban saat beribadah']]}
];
const LABEL={4:'Mengakar',3:'Berkembang Baik',2:'Mulai Bertumbuh',1:'Belum Tumbuh'};
const REK={
 'Mengakar':'Teruslah menjaga kebiasaan baik yang telah tumbuh dalam dirimu. Jadikan rasa syukur, akhlak mulia, dan ketaatan beribadah sebagai teladan bagi teman-temanmu.',
 'Berkembang Baik':'Kamu sudah menunjukkan perilaku yang baik. Teruslah berlatih agar kebiasaan bersyukur, berbuat baik, dan beribadah dapat dilakukan dengan lebih konsisten setiap hari.',
 'Mulai Bertumbuh':'Kamu sedang belajar menjadi pribadi yang lebih baik. Biasakan mengucapkan syukur, bersikap jujur, menghormati orang lain, dan melaksanakan ibadah dengan sungguh-sungguh.',
 'Belum Tumbuh':'Ayo mulai membiasakan diri berdoa, mengucapkan salam, bersikap sopan, dan mengikuti ibadah dengan tertib. Setiap langkah kecil yang dilakukan dengan rutin akan membantu kamu menjadi anak yang saleh dan berakhlak mulia.'
};
const kategori=n=>n>=86?'Mengakar':n>=71?'Berkembang Baik':n>=56?'Mulai Bertumbuh':'Belum Tumbuh';
const hitung=s=>{const perAspek={};let total=0;ASPEK.forEach(a=>{perAspek[a.kode]=a.indikator.reduce((x,[n])=>x+(s?.[n]||0),0);total+=perAspek[a.kode]});const nilai=Math.round(total/52*1000)/10;return {perAspek,total,nilai,kategori:kategori(nilai)}};
const empty=(user)=>({tanggal:new Date().toISOString().slice(0,10),semester:'Ganjil',muridId:'',muridNama:'',kelasId:'',kelasNama:'',guruId:user.guruId||'',guruNama:user.nama||'',madrasahId:user.madrasahId||'',skor:{},catatan:''});
export default function CekTumbuhCintaAllah(){
 const {user}=useAuth(), data=getData(); const [list,setList]=useState(data.cekTumbuhCintaAllah||[]),[form,setForm]=useState(null),[detail,setDetail]=useState(null),[q,setQ]=useState('');
 let visible=list;if(user.role==='guru')visible=visible.filter(x=>x.guruId===user.guruId);else if(user.role==='kepala_madrasah')visible=visible.filter(x=>x.madrasahId===user.madrasahId);visible=visible.filter(x=>(x.muridNama||'').toLowerCase().includes(q.toLowerCase()));
 const calc=useMemo(()=>hitung(form?.skor),[form]);
 const pilih=id=>{const m=data.murid.find(x=>x.id===id),k=data.kelas.find(x=>x.id===m?.kelasId);if(m)setForm(f=>({...f,muridId:m.id,muridNama:m.nama,kelasId:m.kelasId,kelasNama:m.kelasNama||k?.nama||'',madrasahId:m.madrasahId||k?.madrasahId||user.madrasahId||''}))};
 const simpan=()=>{if(!form.muridId||!form.tanggal||!form.semester||Object.keys(form.skor||{}).length!==13)return alert('Lengkapi identitas dan semua 13 indikator.');const payload={...form,nilai:calc.nilai,kategori:calc.kategori,rekomendasi:REK[calc.kategori]};form.id?updateItem('cekTumbuhCintaAllah',form.id,payload):addItem('cekTumbuhCintaAllah',{...payload,id:generateId()});setList(getData().cekTumbuhCintaAllah);setForm(null)};
 const hapus=id=>{if(confirm('Hapus data instrumen ini?')){deleteItem('cekTumbuhCintaAllah',id);setList(getData().cekTumbuhCintaAllah)}};
 if(detail){const c=hitung(detail.skor);return <div className="space-y-4" id="cinta-allah-print"><div className="flex justify-between print:hidden"><button className="px-4 py-2 border rounded-lg" onClick={()=>setDetail(null)}>Kembali</button><button className="px-4 py-2 bg-[#102a4d] text-white rounded-lg flex gap-2" onClick={()=>window.print()}><Printer size={18}/>Cetak</button></div><div className="bg-white max-w-4xl mx-auto p-6 md:p-8 rounded-xl border print:border-0"><h2 className="font-bold text-center text-lg">INSTRUMEN OBSERVASI</h2><h3 className="font-semibold text-center mb-6">IMPLEMENTASI NILAI KARAKTER RELIGIUS MELALUI CINTA ALLAH DAN RASUL-NYA</h3><div className="grid grid-cols-2 gap-2 text-sm mb-5"><p>Nama Murid: <b>{detail.muridNama}</b></p><p>Kelas: {detail.kelasNama}</p><p>Semester: {detail.semester}</p><p>Tanggal: {formatDate(detail.tanggal)}</p><p>Nama Guru: {detail.guruNama}</p></div>{ASPEK.map(a=><div key={a.kode} className="mb-4 overflow-x-auto"><h4 className="font-bold text-sm">{a.kode}. {a.nama.toUpperCase()}</h4><table className="w-full text-sm border-collapse"><tbody>{a.indikator.map(([n,t])=><tr key={n}><td className="border p-2 w-10">{n}</td><td className="border p-2">{t}</td><td className="border p-2 text-center w-36"><b>{detail.skor[n]}</b> — {LABEL[detail.skor[n]]}</td></tr>)}</tbody></table><p className="text-right font-semibold">Skor Aspek {a.kode}: {c.perAspek[a.kode]} / {a.indikator.length*4}</p></div>)}<div className="grid sm:grid-cols-3 gap-3 my-5 text-center"><div className="border p-3 rounded">Total <b>{c.total}/52</b></div><div className="border p-3 rounded">Nilai <b>{c.nilai}%</b></div><div className="border p-3 rounded">Kategori <b>{c.kategori}</b></div></div><h4 className="font-bold">Catatan Perkembangan Karakter</h4><p className="whitespace-pre-wrap mb-4">{detail.catatan||'-'}</p><h4 className="font-bold">Rekomendasi untuk Murid</h4><p>{REK[c.kategori]}</p></div></div>}
 return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold">Cek Tumbuh Kembang Cinta Allah</h2><p className="text-sm text-gray-500">Instrumen perkembangan nilai karakter religius murid</p></div><button onClick={()=>setForm(empty(user))} className="px-4 py-2 bg-[#102a4d] text-white rounded-lg flex gap-2 items-center"><Plus size={17}/>Tambah</button></div><div className="relative max-w-sm"><Search size={17} className="absolute left-3 top-3 text-gray-400"/><input className="w-full border rounded-lg py-2 pl-10" placeholder="Cari murid..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="bg-white border rounded-xl overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50"><tr><th className="p-3 text-left">Tanggal</th><th className="p-3 text-left">Murid</th><th>Kelas</th><th>Skor</th><th>Nilai</th><th>Kategori</th><th>Aksi</th></tr></thead><tbody>{visible.map(x=>{const c=hitung(x.skor);return <tr key={x.id} className="border-t"><td className="p-3">{formatDate(x.tanggal)}</td><td className="p-3 font-medium">{x.muridNama}</td><td className="text-center">{x.kelasNama}</td><td className="text-center">{c.total}/52</td><td className="text-center">{c.nilai}%</td><td className="text-center">{c.kategori}</td><td className="p-2"><div className="flex justify-center gap-1"><button onClick={()=>setDetail(x)} className="p-2 bg-gray-100 rounded"><Eye size={15}/></button><button onClick={()=>setForm({...x,skor:{...x.skor}})} className="p-2 bg-blue-50 rounded"><Edit size={15}/></button><button onClick={()=>hapus(x.id)} className="p-2 bg-red-50 text-red-600 rounded"><Trash2 size={15}/></button></div></td></tr>})}{!visible.length&&<tr><td colSpan="7" className="p-10 text-center text-gray-400">Belum ada data</td></tr>}</tbody></table></div>
 {form&&<div className="fixed inset-0 bg-black/50 z-50 p-3 flex items-center justify-center"><div className="bg-white rounded-xl max-w-5xl w-full max-h-[94vh] overflow-y-auto"><div className="sticky top-0 bg-white p-4 border-b flex justify-between z-10"><h3 className="font-bold">{form.id?'Edit':'Tambah'} Instrumen</h3><button onClick={()=>setForm(null)}><X/></button></div><div className="p-4 space-y-4"><div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3"><select className="border rounded p-2" value={form.muridId} onChange={e=>pilih(e.target.value)}><option value="">Pilih Murid</option>{data.murid.filter(m=>user.role!=='kepala_madrasah'||m.madrasahId===user.madrasahId).map(m=><option key={m.id} value={m.id}>{m.nama}</option>)}</select><input className="border rounded p-2 bg-gray-50" value={form.kelasNama} readOnly placeholder="Kelas"/><select className="border rounded p-2" value={form.semester} onChange={e=>setForm({...form,semester:e.target.value})}><option>Ganjil</option><option>Genap</option></select><input type="date" className="border rounded p-2" value={form.tanggal} onChange={e=>setForm({...form,tanggal:e.target.value})}/><input className="border rounded p-2" value={form.guruNama} onChange={e=>setForm({...form,guruNama:e.target.value})} placeholder="Nama Guru"/></div><div className="text-xs bg-gray-50 p-3 rounded">Skor: <b>4 Mengakar</b> · <b>3 Berkembang Baik</b> · <b>2 Mulai Bertumbuh</b> · <b>1 Belum Tumbuh</b></div>{ASPEK.map(a=><section key={a.kode} className="border rounded-lg overflow-hidden"><h4 className="font-semibold bg-gray-100 p-3">Aspek {a.kode}: {a.nama} <span className="float-right">{calc.perAspek[a.kode]}/{a.indikator.length*4}</span></h4>{a.indikator.map(([n,t])=><div key={n} className="p-3 border-t grid md:grid-cols-[1fr_auto] gap-2"><span>{n}. {t}</span><div className="flex flex-wrap gap-2">{[4,3,2,1].map(v=><label key={v} className={`border rounded px-2 py-1 text-xs cursor-pointer ${form.skor[n]===v?'bg-[#102a4d] text-white':''}`}><input className="mr-1" type="radio" name={'s'+n} checked={form.skor[n]===v} onChange={()=>setForm(f=>({...f,skor:{...f.skor,[n]:v}}))}/>{v} {LABEL[v]}</label>)}</div></div>)}</section>)}<div className="grid sm:grid-cols-3 gap-2 text-center"><div className="border p-3">Total: <b>{calc.total}/52</b></div><div className="border p-3">Nilai: <b>{calc.nilai}%</b></div><div className="border p-3">Kategori: <b>{calc.kategori}</b></div></div><textarea className="w-full border rounded p-3" rows="3" placeholder="Catatan perkembangan karakter" value={form.catatan} onChange={e=>setForm({...form,catatan:e.target.value})}/><div className="bg-amber-50 p-3 rounded text-sm"><b>Rekomendasi otomatis:</b> {REK[calc.kategori]}</div></div><div className="sticky bottom-0 bg-white p-4 border-t flex justify-end"><button onClick={simpan} className="bg-[#2fa295] text-white px-5 py-2 rounded-lg flex gap-2"><Save size={18}/>Simpan</button></div></div></div>}</div>
}
