import React, { useMemo, useState } from 'react';
import { Check, Plus, Printer, Save, Trash2 } from 'lucide-react';
import { getData, setData, generateId, BULAN_NAMA, getDaysInMonth } from '../lib/store';

const TAHAPAN = [
  { nama: 'Persiapan Sebelum Mengajar', tujuan: 'Meluruskan niat mengajar sebagai ibadah serta menyiapkan diri secara optimal sebagai wujud cinta Allah dan cinta diri.', uraian: ['Penyelarasan niat: mindfulness selama 1 menit, berdoa memohon bantuan Allah Swt., serta menyadari bahwa mengajar adalah ibadah dan pemberian cinta.', 'Berpenampilan rapi, sopan, hangat, ramah, dan bahagia.', 'Menata emosi agar siap melayani murid, menyiapkan perangkat pembelajaran, serta memastikan kelas bersih dan nyaman.'] },
  { nama: 'Pembukaan Kelas (Heart-to-Heart Opening)', tujuan: 'Membangun hubungan positif sebelum pembelajaran dimulai sebagai wujud cinta sesama.', uraian: ['Hadir di kelas, berdiri di depan kelas, mengucapkan salam, dan menyapa setiap siswa dengan senyuman.', 'Melakukan check-in emosi, menanyakan kabar, dan memberi perhatian kepada murid yang kurang bersemangat.'] },
  { nama: 'Pembukaan Pembelajaran', tujuan: 'Menghadirkan suasana belajar yang tenang dan bermakna sebagai wujud cinta Allah, cinta ilmu, dan cinta sesama.', uraian: ['Tazkiyatun nafs: duduk rapi, hening, dzikir pendek, doa, dan bersyukur selama 1–2 menit.', 'Mengaitkan materi dengan kebesaran Allah secara relevan dan menyampaikan tujuan pembelajaran dengan bahasa yang membangkitkan semangat.', 'Memberikan afirmasi positif kepada murid.'] },
  { nama: 'Pembelajaran Inti (Active Learning)', tujuan: 'Menumbuhkan kecintaan terhadap ilmu dan proses belajar sebagai wujud cinta ilmu.', uraian: ['Memberikan instruksi ramah dengan kata positif; fokus pada perbaikan, bukan penghakiman.', 'Menerapkan diferensiasi berdasarkan kemampuan awal, minat, dan gaya belajar siswa.', 'Melaksanakan pembelajaran aktif dengan cinta: antusias, mendorong pertanyaan mendalam, berpikir kritis, eksplorasi, investigasi, diskusi, serta mengaitkan materi dengan kebesaran Allah dan keteladanan Rasulullah.', 'Mengelola konflik secara positif, tenang, logis, dan penuh pertimbangan.', 'Mengapresiasi pertanyaan, ide, proses, dan usaha murid—bukan hanya hasil akhir.', 'Memberikan jeda atau ice breaking ketika siswa lelah atau jenuh.'] },
  { nama: 'Istirahat Tanpa Plastik (Eco-Break)', tujuan: 'Menumbuhkan cinta Allah dan Rasul-Nya, cinta diri, cinta sesama, dan cinta lingkungan melalui kebiasaan positif saat istirahat.', uraian: ['Memastikan bekal dan minuman menggunakan wadah ramah lingkungan.', 'Memantau siswa selama istirahat.', 'Mengingatkan adab makan berkesadaran, tertib, berbagi, dan diawali doa.', 'Membiasakan hamdalah ketika memperoleh keberhasilan atau kebahagiaan.', 'Mengelola sisa makanan secara bijak: dikomposkan, ditasarufkan, atau dibuang pada tempat sesuai.', 'Memastikan kelas kembali bersih dan rapi setelah istirahat.'] },
  { nama: 'Penutupan dan Refleksi (The Loving Closure)', tujuan: 'Mengakhiri pembelajaran dengan rasa syukur dan keterhubungan.', uraian: ['Mengajak siswa berbagi satu hal yang disyukuri atau satu hal baru yang dipelajari.', 'Memberi kesempatan siswa memberikan “Kado Kata” atau pujian kepada teman.', 'Menutup dengan doa tulus untuk kesehatan dan kebahagiaan semua orang di kelas.', 'Memberikan pesan penguatan dan kepulangan yang hangat.'] },
];
const now = new Date();
const empty = () => ({ id: generateId(), namaGuru: '', mataPelajaran: '', kelas: '', bulan: now.getMonth()+1, tahun: now.getFullYear(), checklist: {}, refleksi: [] });

export default function JurnalRefleksiMapel() {
  const saved = getData().jurnalRefleksiMapel;
  const [form, setForm] = useState(saved?.[0] || empty());
  const days = useMemo(() => Array.from({length:getDaysInMonth(+form.tahun, +form.bulan)},(_,i)=>i+1), [form.bulan, form.tahun]);
  const patch = (key, value) => setForm(f => ({...f, [key]:value}));
  const toggle = (t, k, d) => setForm(f => { const key=`${t}-${k}-${d}`; const c={...f.checklist}; c[key] ? delete c[key] : c[key]=true; return {...f,checklist:c}; });
  const save = () => { setData('jurnalRefleksiMapel', [{...form, updatedAt:new Date().toISOString()}]); alert('Jurnal refleksi tersimpan.'); };
  const addRefleksi = () => patch('refleksi', [...form.refleksi, {id:generateId(),tanggal:'',catatan:'',rencana:''}]);
  const updateRef = (id,key,value) => patch('refleksi', form.refleksi.map(r=>r.id===id?{...r,[key]:value}:r));
  const input='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-[#102a4d]';
  return <div className="space-y-5 print-area">
    <div className="flex flex-wrap items-start justify-between gap-3 print:hidden"><div><h2 className="text-xl font-bold text-[#102a4d]">Jurnal Refleksi Guru Mapel</h2><p className="text-sm text-gray-500">Pembiasaan harian berbasis Panca Cinta</p></div><div className="flex gap-2"><button onClick={()=>window.print()} className="flex items-center gap-2 rounded-lg bg-gray-100 px-4 py-2 text-sm"><Printer className="w-4 h-4"/>Cetak</button><button onClick={save} className="flex items-center gap-2 rounded-lg bg-[#102a4d] px-4 py-2 text-sm text-white"><Save className="w-4 h-4"/>Simpan</button></div></div>
    <section className="rounded-xl border bg-white p-5"><h1 className="text-center text-lg font-bold text-[#102a4d]">JURNAL REFLEKSI PEMBIASAAN HARIAN BERBASIS PANCA CINTA</h1><p className="mb-5 text-center text-sm font-semibold">GURU MATA PELAJARAN</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs text-gray-600">Nama Guru<input className={input} value={form.namaGuru} onChange={e=>patch('namaGuru',e.target.value)}/></label><label className="text-xs text-gray-600">Mata Pelajaran<input className={input} value={form.mataPelajaran} onChange={e=>patch('mataPelajaran',e.target.value)}/></label><label className="text-xs text-gray-600">Kelas<input className={input} value={form.kelas} onChange={e=>patch('kelas',e.target.value)}/></label><div className="grid grid-cols-2 gap-2"><label className="text-xs text-gray-600">Bulan<select className={input} value={form.bulan} onChange={e=>patch('bulan',+e.target.value)}>{BULAN_NAMA.map((x,i)=><option key={x} value={i+1}>{x}</option>)}</select></label><label className="text-xs text-gray-600">Tahun<input type="number" className={input} value={form.tahun} onChange={e=>patch('tahun',+e.target.value)}/></label></div></div></section>
    <section className="rounded-xl border bg-white overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[900px] border-collapse text-xs"><thead className="bg-[#102a4d] text-white"><tr><th className="p-2 w-10">No</th><th className="p-2 text-left w-44">Tahapan</th><th className="p-2 text-left w-56">Tujuan</th><th className="p-2 text-left min-w-80">Uraian Pembiasaan Guru</th>{days.map(d=><th key={d} className="p-1 min-w-8">{d}</th>)}</tr></thead><tbody>{TAHAPAN.flatMap((t,ti)=>t.uraian.map((u,ki)=><tr key={`${ti}-${ki}`} className="border-t align-top">{ki===0&&<><td rowSpan={t.uraian.length} className="p-2 text-center font-bold">{ti+1}</td><td rowSpan={t.uraian.length} className="p-2 font-semibold text-[#102a4d]">{t.nama}</td><td rowSpan={t.uraian.length} className="p-2 text-gray-600">{t.tujuan}</td></>}<td className="p-2">{u}</td>{days.map(d=>{const on=form.checklist[`${ti}-${ki}-${d}`];return <td key={d} className="p-1 text-center"><button onClick={()=>toggle(ti,ki,d)} className={`mx-auto flex h-6 w-6 items-center justify-center rounded border ${on?'bg-[#2fa295] text-white':'bg-white'}`}>{on&&<Check className="w-4 h-4"/>}</button></td>})}</tr>))}</tbody></table></div></section>
    <section className="rounded-xl border bg-white overflow-hidden"><div className="flex items-center justify-between p-4"><div><h3 className="font-bold text-[#102a4d]">Catatan Refleksi Harian Guru</h3><p className="text-xs text-gray-500">Temuan spesifik yang belum tertangani; bahan refleksi mingguan bersama teman sejawat.</p></div><button onClick={addRefleksi} className="print:hidden flex gap-1 items-center rounded-lg bg-[#102a4d] px-3 py-2 text-xs text-white"><Plus className="w-4 h-4"/>Tambah</button></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead className="bg-gray-100"><tr><th className="p-2 w-12">No</th><th className="p-2 text-left w-40">Tanggal</th><th className="p-2 text-left">Catatan</th><th className="p-2 text-left">Rencana Refleksi</th><th className="w-12 print:hidden"/></tr></thead><tbody>{form.refleksi.map((r,i)=><tr key={r.id} className="border-t align-top"><td className="p-2 text-center">{i+1}</td><td className="p-2"><input type="date" className={input} value={r.tanggal} onChange={e=>updateRef(r.id,'tanggal',e.target.value)}/></td><td className="p-2"><textarea className={input} rows="2" value={r.catatan} onChange={e=>updateRef(r.id,'catatan',e.target.value)}/></td><td className="p-2"><textarea className={input} rows="2" value={r.rencana} onChange={e=>updateRef(r.id,'rencana',e.target.value)}/></td><td className="p-2 print:hidden"><button onClick={()=>patch('refleksi',form.refleksi.filter(x=>x.id!==r.id))} className="text-red-600"><Trash2 className="w-4 h-4"/></button></td></tr>)}{!form.refleksi.length&&<tr><td colSpan="5" className="p-8 text-center text-gray-400">Belum ada catatan refleksi.</td></tr>}</tbody></table></div></section>
  </div>;
}
